server:
  port: 8000

spring:
  application:
    name: central
  datasource:
    url: jdbc:postgresql://localhost:5432/central_db
    username: root
    password: rootpassword
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: rootpassword

management:
  endpoints:
    web:
      exposure:
        include: health,info
