server:
  port: 8082

spring:
  application:
    name: inventory
  datasource:
    url: jdbc:mysql://localhost:3307/inventory_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: rootpassword

management:
  endpoints:
    web:
      exposure:
        include: health,info
