server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: billing
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://cockroachdb-service.distribuidas.svc.cluster.local:26257/db-catalog?user=root&password=}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq-service.distribuidas.svc.cluster.local}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin}

management:
  endpoints:
    web:
      exposure:
        include: health,info


